variable "name" {}
variable "region" {}
variable "cognito_domain" {}
variable "cognito_user_pool_id" {}
variable "cognito_identity_pool_id" {}
variable "access_policies" {}
variable "opensearch_domain_name" {}
variable "opensearch_version" {}
variable "opensearch_instance" {}
variable "opensearch_instance_count" {}
variable "opensearch_ebs_volume_size" {}
variable "opensearch_ebs_volume_type" {}
